// Code generated by go-swagger; DO NOT EDIT.

// Package rest_api pdf2text
//
//	pdf2text
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/pdf
//
//	Produces:
//	  - application/json
//
// swagger:meta
package rest_api
