// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/haxii/pdf2text/models"
)

// PDF2TextOKCode is the HTTP code returned for type PDF2TextOK
const PDF2TextOKCode int = 200

/*
PDF2TextOK pdf2text result

swagger:response pDF2TextOK
*/
type PDF2TextOK struct {

	/*
	  In: Body
	*/
	Payload *models.Pdf2TextResult `json:"body,omitempty"`
}

// NewPDF2TextOK creates PDF2TextOK with default headers values
func NewPDF2TextOK() *PDF2TextOK {

	return &PDF2TextOK{}
}

// WithPayload adds the payload to the p d f2 text o k response
func (o *PDF2TextOK) WithPayload(payload *models.Pdf2TextResult) *PDF2TextOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the p d f2 text o k response
func (o *PDF2TextOK) SetPayload(payload *models.Pdf2TextResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PDF2TextOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
